<?php

namespace AppBundle\Repository;

/**
 * VariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariantRepository extends \Doctrine\ORM\EntityRepository
{
}
