products:
    path: products
    defaults:
        _format: json,
        _controller: AppBundle:Products:index

create_product:
    path: products/create
    defaults:
        _format: json,
        _controller: AppBundle:Products:create

delete_product:
    path: products/delete
    defaults:
        _format: json,
        _controller: AppBundle:Products:delete
