products:
    path: products
    defaults:
        _format: json
        _controller: AppBundle:Products:index

create_product:
    path: products/create
    defaults:
        _format: json
        _controller: AppBundle:Products:create

delete_product:
    path: products/delete
    defaults:
        _format: json
        _controller: AppBundle:Products:delete

show_product:
    path: products/show/{id}
    defaults:
        _format: json
        _controller: AppBundle:Products:show
    requirements:
        id: \d+

update_product:
    path: products/edit/{id}
    defaults:
        _format: json
        _controller: AppBundle:Products:update
    requirements:
        id: \d+

add.varaint.product:
    path: products/{id}/variant/add
    defaults:
        _format: json
        _controller: AppBundle:Variant:add
    requirements:
        id: \d+

delete.varaint.product:
    path: products/{pid}/variant/{vid}/delete
    defaults:
        _format: json
        _controller: AppBundle:Variant:delete
    requirements:
        pid: \d+
        vid: \d+

delete.varaint.product:
    path: products/{pid}/variant/{vid}/delete
    defaults:
        _format: json
        _controller: AppBundle:Variant:delete
    requirements:
        pid: \d+
        vid: \d+

update.varaint.product:
    path: products/{pid}/variant/{vid}/update
    defaults:
        _format: json
        _controller: AppBundle:Variant:update
    requirements:
        pid: \d+
        vid: \d+

